const runRows = [
    { arguments: "-q, --quiet   ", description: "    Do not print cargo log messages" },
    { arguments: "--bin[<NAME>]     ", description: "Name of the bin target to run" },
    { arguments: "--example[<NAME>] ", description: "Name of the example target to run" },
    { arguments: "-p, --package [<SPEC>...]   ", description: "Package with the target to run" },
    { arguments: "-v, --verbose               ", description: "Use verbose output (-vv very verbose/build.rs output)" },
    { arguments: "-j, --jobs <N>              ", description: "Number of parallel jobs, defaults to # of CPUs" },
    { arguments: "--color <WHEN>          ", description: "Coloring: auto, always, never" },
    { arguments: "--keep-going            ", description: "Do not abort the build as soon as there is an error (unstable)" },
    { arguments: "--frozen                ", description: "Require Cargo.lock and cache are up to date" },
    { arguments: "-r, --release               ", description: "Build artifacts in release mode, with optimizations" },
    { arguments: "--locked                ", description: "Require Cargo.lock is up to date" },
    { arguments: "--profile <PROFILE-NAME>", description: "Build artifacts with the specified profile" },
    { arguments: "--features <FEATURES>   ", description: "Space or comma separated list of features to activate" },
    { arguments: "--offline               ", description: "Run without accessing the network" },
    { arguments: "--all-features          ", description: "Activate all available features" },
    { arguments: "--config <KEY=VALUE>    ", description: "Override a configuration value (unstable)" },
    { arguments: "--no-default-features   ", description: "Do not activate the `default` feature" },
    { arguments: "-Z <FLAG>                   ", description: "Unstable (nightly-only) flags to Cargo, see 'cargo -Z help' for" },
    { arguments: "--target <TRIPLE>       ", description: "Build for the target triple" },
    { arguments: "--target-dir <DIRECTORY>", description: "Directory for all generated artifacts" },
    { arguments: "--manifest-path <PATH>  ", description: "Path to Cargo.toml" },
    { arguments: "--message-format <FMT>  ", description: "Error format" },
    { arguments: "--unit-graph            ", description: "Output build graph in JSON (unstable)" },
    { arguments: "--ignore-rust-version   ", description: "Ignore `rust-version` specification in packages" },
    { arguments: "--timings[=<FMTS>...]   ", description: "Timing output formats (unstable) (comma separated): html, json" },
    { arguments: "-h, --help                  ", description: "Print help information" },
]

export default runRows